version: "{branch} #{build}"

image:
  - Visual Studio 2017
  - Visual Studio 2019

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 2015 Win64"
    - GENERATOR: "Visual Studio 14 2015"
    - GENERATOR: "Visual Studio 15 2017 Win64"
    - GENERATOR: "Visual Studio 15 2017"
    - GENERATOR: "Visual Studio 16 2019"

matrix:
  exclude:
    - image: Visual Studio 2017
      GENERATOR: "Visual Studio 16 2019"
    - image: Visual Studio 2019
      GENERATOR: "Visual Studio 14 2015 Win64"
    - image: Visual Studio 2019
      GENERATOR: "Visual Studio 14 2015"
    - image: Visual Studio 2019
      GENERATOR: "Visual Studio 15 2017 Win64"
    - image: Visual Studio 2019
      GENERATOR: "Visual Studio 15 2017"

before_build:
  - mkdir build
  - cd build
  - cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=Debug ..

build_script:
- cmd: >-
    cmake --build . --target self_test

test_script:
- cmd: cmake --build . --target run_self_test
